### ISSUE TITLE
Makebias crash.

### ISSUE THREAD

**Issue by cmccully** [cmccully/pylcogt#3]
1m0-11
makebias
['20141130']
['coj1m011-kb05-20141130-0052-e00.fits'
 'coj1m011-kb05-20141130-0051-e00.fits'
 'coj1m011-kb05-20141130-0053-e00.fits'
 'coj1m011-kb05-20141130-0061-e00.fits'
 'coj1m011-kb05-20141130-0060-e00.fits'
 'coj1m011-kb05-20141130-0054-e00.fits'
 'coj1m011-kb05-20141130-0084-f00.fits'
 'coj1m011-kb05-20141130-0083-f00.fits'
 'coj1m011-kb05-20141130-0082-f00.fits'
 'coj1m011-kb05-20141130-0081-f00.fits'
 'coj1m011-kb05-20141130-0080-f00.fits']
select bias and make bias
Traceback (most recent call last):
  File "/science/supernova/github/pylcogt/pylcogt/pylcogtmain.py", line 104, in <module>
    listfile = [k + v for k, v in zip(ll0['filepath'][ww], ll0['filename'][ww])]
IndexError: arrays used as indices must be of integer (or boolean) type
/home/supernova/lib/python2.7/site-packages/pylcogt-0.0.dev189-py2.7.egg/pylcogt/utils/pymysql.py:108: Warning: Data truncated for column 'dateobs' at row 1
  cursor.execute(sql, values)

**Comment by cmccully** [comment]
Two updates. I was passing a filter to the bias images, but the bias images were taken with a different filter. The first thing is that makebias should just ignore the filter keyword and should look for all images. This is probably also true for makedark. Second, if there are no images, the pipeline should exit gracefully instead of crashing.

**Comment by svalenti** [comment]
Got it will work on it next week in when I'm back
